### ISSUE TITLE
Can't use as dependency

### ISSUE THREAD

**Issue by Spyes** [Aircloak/phoenix_gen_socket_client#11]
I'd like to use this library as a dependency that will be published to Hex.pm however since this package isn't on there, it won't let me publish. Any chance you could release this as official on Hex.pm? Thanks!

**Comment by sasa1977** [comment]
The library is now [available on hex](https://hex.pm/packages/phoenix_gen_socket_client). Thanks for approaching us about this, and happy usage :-)

**Comment by Spyes** [comment]
@sasa1977  Thanks a lot!
