### ISSUE TITLE
How to pass Phoenix.Token on socket connect?

### ISSUE THREAD

**Issue by jcfischer** [Aircloak/phoenix_gen_socket_client#14]
Disclaimer: I'm fairly new to Elixir/Phoenix, so this might be a case of missing the obvious - sorry about that.

I'm trying to connect an Elixir App to a running Phoenix server. I have a number of channels working (and am using the Phoenix.Token method to handle socket authentication). That works fine from a browser. 
I have added the PingChannel from the example directory and am trying to connect to it via the socket_client.ex also from the example directory, but in another app.

I can see that the connection is trying to happen, but it gets rejected by the server due to the token not being present upon connection. I have trawled the code to figure out when and how to pass the token when the socket is created, but I haven't been able to figure out where to add it.

The code used is 1:1 the one from the examples, the difference is the `connect` function in the `user_socket.ex` file in the Phoenix app:

```
  def connect(%{"token" => token}, socket) do
    case Phoenix.Token.verify(socket, "user socket", token, max_age: @max_age) do
      {:ok, uuid} ->
        IO.puts "verified : #{uuid}"
        {:ok, assign(socket, :user_uuid, uuid) }
      {:error, _reason} ->
        IO.puts "error: #{_reason}"
        :error
    end
  end
```

in JavaScript, in the browser, this is how the socket is connected:

```
let socket = new Socket("/socket", {params: {token: window.userToken}})
```

Any ideas?

**Comment by sasa1977** [comment]
Glancing at the Phoenix code, it looks like [token is just appended as a parameter to URL](https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L689-L691). Could you try providing url as `ws://server_url/my_socket/websocket?token=your_token` ?

**Comment by jcfischer** [comment]
That's what I just figured out myself as well - it actually works. I have faked the token, because I need to figure out how to really sign a token (That would probably mean that I need to import Phoenix.Token into a non-Phoenix application somehow). 

For now (this is a quick and dirty hack) I can live with a hardcoded token (that is handled on the server)

**Comment by jcfischer** [comment]
thanks for the help - I'm closing this
