### ISSUE TITLE
Revert graceful encoding errors?

### ISSUE THREAD

**Issue by obrok** [Aircloak/phoenix_gen_socket_client#22]
@sasa1977 https://github.com/Aircloak/phoenix_gen_socket_client/pull/21 was not needed after all - I didn't notice that we don't use the default encoder when making that PR. Should we revert it and release 1.3.0 without it? Also see https://github.com/Aircloak/aircloak/pull/1722.

**Comment by sasa1977** [comment]
Personally, I think that since the change is breaking, we should have released it as 2.0, and not 1.2. Now that it's already released, I think it's better to leave it like it is.
