### ISSUE TITLE
Need to be able to update the original query_parameters

### ISSUE THREAD

**Issue by boydm** [Aircloak/phoenix_gen_socket_client#29]
Hi Sasa,

The scenario is this:

* I've connected to the server with a token that was passed to `GenSocketClient` during the init function.
* Time passes and the token is now expired. I can get a new one before the expiration, but don't know how to update the original query_params with it.
* Something happens on the network to cause a disconnection. When I try to reconnect, it uses the old token, which will fail.

How can I update the query_params I passed in during init? Is this going to need a new function?

Thank you

**Comment by boydm** [comment]
Number 2 - always declaring the url and params - is clearly the better solution. It also feels more "functional" in nature with less behind-the-scenes magic in state.

When my client makes the authentication api call, the server has the opportunity to tell it to go to a new url as well as giving a new token. This was very important in past services I've built in order to migrate users to a new cluster for either functionality or load reasons...

There is a way we could do this without breaking change (but I don't like it). We could make a new, optional, return value for the other callbacks. something like `{:connect, url, params, state}` without removing the existing one. Then match against it to do the right thing. Isn't as clean as it would still require keeping the url around in private state, but it wouldn't introduce a breaking change.

Personally, I think I would go for the breaking solution. Migrating the url and the query_params are super important for long-term production services and might be worth bumping the major version. Never storing the url/params in state increases transparency and makes it clear how to go about controlling the service overall.

**Comment by sasa1977** [comment]
Yeah I think optional version would be a good immediate solution, mainly because I'm considering some other changes to the interface, and I don't want to introduce breaking changes very frequently. So I'd say let's support `{:connect, url, params, state}` in addition to `{:connect, state}`, and I'll think some more about the interface for 3.x.

**Comment by boydm** [comment]
Cool. I can work on the update later tonight unless it's easy for you to do. Just let me know if you are working on it so we don't both do the same thing...

**Comment by sasa1977** [comment]
I won't be able to work on this immediately, so feel free to take it :-)

**Comment by boydm** [comment]
Just submitted a proposed fix in a pull-request.

**Comment by boydm** [comment]
Fixed in PR #30, which was just merged.
