### ISSUE TITLE
Git tag v2.1.0 missing

### ISSUE THREAD

**Issue by axelson** [Aircloak/phoenix_gen_socket_client#33]
The Git tag for the latest release (`v2.1.0`) is missing. This causes all the links in the documentation that point to the source code to return 404's. For example 

https://hexdocs.pm/phoenix_gen_socket_client/Phoenix.Channels.GenSocketClient.html#joined?/1 currently links to this broken link:  https://github.com/Aircloak/phoenix_gen_socket_client/blob/v2.1.0/lib/gen_socket_client.ex#L175

**Comment by sasa1977** [comment]
Good catch, thanks for reporting! The tag is now pushed.
