### ISSUE TITLE
New release after switching to Jason

### ISSUE THREAD

**Issue by electricshaman** [Aircloak/phoenix_gen_socket_client#45]
It's been awhile since a release was cut.  Would love to take advantage of the Jason support.  Are there plans to do a release anytime soon?

**Comment by sebastian** [comment]
Hi @electricshaman, you are absolutely right!

I was planning to make one next week. There are a bunch of other things on my plate at the moment.

**Comment by electricshaman** [comment]
Thank you for maintaining this library!

**Comment by sebastian** [comment]
> Thank you for maintaining this library!

Well, not doing enough maintaining it seems!
Thank you for making pull-requests and prodding where needed!

I made a new release. It's a new major release due to the breaking change of moving from Poison to Jason.
Please let me know if you experience any issues.

Thanks
